name: nen_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - anndata=0.11.4
  - biopython=1.85
  - h5py=3.13.0
  - harmony-pytorch=0.1.8
  - ipykernel=6.29.5
  - matplotlib-base=3.10.1
  - numpy=2.2.4
  - pandas=2.2.3
  - pytorch=2.6.0
  - scanpy=1.11.1
  - scikit-learn=1.5.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - tqdm=4.67.1
  - umap-learn=0.5.7
  - pip:
    - pertpy==0.10.0
    - torch-geometric==2.6.1
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - adjustText==1.3.0
    - blitzgsea==1.3.53
    - decoupler==1.9.2
    - equinox==0.11.10
    - flax==0.10.4
    - jax==0.4.35
    - jaxlib==0.4.35
    - leidenalg==0.10.2
    - lightning==2.5.1
    - mudata==0.3.1
    - muon==0.1.7
    - scvi-tools==1.3.0
    - treescope==0.1.9